[package]
name = "pixelkit-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
pixelkit-raster = { workspace = true }
pixelkit-text = { workspace = true }
pixelkit-shell = { workspace = true }
accesskit = { version = "0.25", optional = true }
zeroize = { workspace = true }
unicode-segmentation = "1.13.3"

[dev-dependencies]
pixelkit-text = { workspace = true, features = ["test-fonts"] }
pixelkit-windowing = { workspace = true }

[features]
test-fonts = ["pixelkit-text/test-fonts"]
accessibility = ["dep:accesskit"]

[lints]
workspace = true
